apiVersion: batch/v1
kind: Job
metadata:
  name: db-create-job
spec:
  template:
    spec:
      containers:
        - name: db-create-container
          image: mountainpinelake/wedding-app:latest
          command: ["bin/rails", "db:create"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/wedding_postgres_db"
      restartPolicy: Never
