apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
spec:
  template:
    spec:
      containers:
        - name: db-migrate-container
          image: mountainpinelake/wedding-app:v2.0
          command: ["bundle", "exec", "rake", "db:migrate"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/wedding_postgres_db"
      restartPolicy: Never
